name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0

      - uses: actions/checkout@v3

      - name: Make linux arm64 version
        run: make linux/arm64

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: http-echo-linux-arm64
          path: http-echo-linux-arm64.zip
