name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.0

    - uses: actions/checkout@v3

    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Make linux arm64 version
      run: make linux/arm64
