name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: # optional
        # Path to the go.mod file.
        go-version-file: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: # optional
        # Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
        token: # optional, default is ${{ github.token }}
        # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
        cache: # optional
        # Used to specify the path to a dependency file - go.sum
        cache-dependency-path: # optional

    - uses: actions/checkout@v3

    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Make linux arm64 version
      run: make linux/arm64
